### ISSUE TITLE
Update spark-template-jade

### ISSUE THREAD

**Issue by Ribesg** [perwendel/spark-template-engines#34]
Jade4J received a lot of fixes, some of which I needed. Please update the Jade4J dependency version of `spark-template-jade`.

For those interested in using a more recent Jade4J version than the one provided by `spark-template-engine`, I used the following to specify the Maven dependency (In YAML using Maven-Polyglot):

``` YAML
  # Spark
- artifactId: spark-template-jade
  groupId: com.sparkjava
  version: 2.3
  exclusions:
  - artifactId: jade4j
    groupId: de.neuland-bfi

  # Jade4J
- artifactId: jade4j
  groupId: de.neuland-bfi
  version: 1.2.3
```
